In [78]:
import numpy as np

exam1scores = []
exam2scores = []

# take in scores
score = int(input())
while score != -1:
    exam1scores.append(score)
    score = int(input())

score = int(input())
while score != -1:
    exam2scores.append(score)
    score = int(input())

num_students = len(exam1scores)

# convert lists into numpy arrays and reshape in n x 3 array
exam1scores = np.array(exam1scores).reshape((num_students//3,3))
exam2scores = np.array(exam2scores).reshape((num_students//3,3))

print(exam1scores)
print()
print(exam2scores)
print()

# each exam account for 50%
results = (exam1scores + exam2scores)/2

# group leader get extra 10 points
for i in range(results.shape[0]):
    results[i][0] += 10

# total result format
for i in range(results.shape[0]): # iterate over rows
    for j in range(results.shape[1]): # iterate over columns
        if results[i][j] > 100:
            results[i][j] = 100
        if results[i][j] < 60:
            results[i][j] = -1

print(results)

65
70
85
90
100
70
70
50
20
-1
80
90
60
30
95
60
75
20
80
-1
[[ 65  70  85]
 [ 90 100  70]
 [ 70  50  20]]

[[80 90 60]
 [30 95 60]
 [75 20 80]]

[[82.5 80.  72.5]
 [70.  97.5 65. ]
 [82.5 -1.  -1. ]]
